import type { Metadata } from "next";
import "@/app/globals.css";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import { Toaster } from "@/components/ui/Sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta httpEquiv="X-UA-Compatible" content="ie=edge"></meta>
        <title>Han Tiet&apos;s Portfolio</title>
      </head>
      <body className="h-screen w-screen overflow-x-hidden">
        <AppRouterCacheProvider>
          <Toaster position="bottom-right" />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
